const productImage =
  "https://images.pexels.com/photos/4239031/pexels-photo-4239031.jpeg?auto=compress&cs=tinysrgb&w=320";
const buyerAvatar =
  "https://images.pexels.com/photos/6129501/pexels-photo-6129501.jpeg?auto=compress&cs=tinysrgb&w=240";

const mock = {
  title: "全部订单",
  serviceTypes: ["家政护工", "康复理疗", "上门体检"],
  paymentOptions: ["全部方式", "支付宝", "微信支付", "银行卡"],
  statusTabs: ["全部", "待付款", "待接单", "待服务", "已完成", "退款售后", "已关闭"],
  orders: [
    {
      id: "2400126670",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "应付款",
      settleAmount: "300.00",
      title: "日常清洁 2小时1人急速清洁全程质保",
      image: productImage,
      price: "300.00",
      buyerName: "笑看人生",
      buyerPhone: "19288664488",
      buyerAvatar,
      status: "待付款",
      payment: "-",
      serviceType: "家政护工",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "关闭订单", tone: "red" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
    {
      id: "2400126671",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "实付款",
      settleAmount: "300.00",
      title: "日常清洁 2小时1人急速清洁全程质保",
      image: productImage,
      price: "300.00",
      buyerName: "笑看人生",
      buyerPhone: "19288664488",
      buyerAvatar,
      status: "待接单",
      payment: "支付宝",
      serviceType: "家政护工",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "手动派单", tone: "green" },
        { label: "退款", tone: "red" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
    {
      id: "2400126672",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "实付款",
      settleAmount: "300.00",
      title: "日常清洁 2小时1人急速清洁全程质保",
      image: productImage,
      price: "300.00",
      buyerName: "笑看人生",
      buyerPhone: "19288664488",
      buyerAvatar,
      status: "待服务",
      payment: "支付宝",
      serviceType: "家政护工",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "退款", tone: "red" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
    {
      id: "2400126673",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "实付款",
      settleAmount: "300.00",
      title: "日常清洁 2小时1人急速清洁全程质保",
      image: productImage,
      price: "300.00",
      buyerName: "笑看人生",
      buyerPhone: "19288664488",
      buyerAvatar,
      status: "已完成",
      payment: "支付宝",
      serviceType: "家政护工",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "发起售后", tone: "red" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
    {
      id: "2400126674",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "实付款",
      settleAmount: "300.00",
      title: "日常清洁 2小时1人急速清洁全程质保",
      image: productImage,
      price: "300.00",
      buyerName: "笑看人生",
      buyerPhone: "19288664488",
      buyerAvatar,
      status: "已关闭",
      payment: "支付宝",
      serviceType: "家政护工",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
    {
      id: "2400126675",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "实付款",
      settleAmount: "300.00",
      title: "日常清洁 2小时1人急速清洁全程质保",
      image: productImage,
      price: "300.00",
      buyerName: "笑看人生",
      buyerPhone: "19288664488",
      buyerAvatar,
      status: "退款售后",
      payment: "支付宝",
      serviceType: "家政护工",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
    {
      id: "2400126676",
      orderTime: "2022-12-09 14:12:07",
      settleLabel: "实付款",
      settleAmount: "300.00",
      title: "康复训练 上门评估与基础理疗服务",
      image: productImage,
      price: "599.00",
      buyerName: "王小倩",
      buyerPhone: "13688664488",
      buyerAvatar,
      status: "待服务",
      payment: "微信支付",
      serviceType: "康复理疗",
      actions: [
        { label: "订单详情", tone: "green" },
        { label: "联系用户", tone: "green" },
        { label: "备注", tone: "green" },
      ],
    },
  ],
};

export default mock;
