const mock = {
  greeting: "早上好！ Daisy",
  stats: [
    {
      label: "新增用户数量",
      value: "1080",
      compareLabel: "较上周",
      compareValue: "+20%",
      compareTone: "positive",
      chartType: "area",
      chartColor: "#10c89a",
      values: [18, 54, 48, 88, 82, 124, 86, 108],
    },
    {
      label: "新增工单数量",
      value: "3400",
      compareLabel: "较上周",
      compareValue: "+30%",
      compareTone: "positive",
      chartType: "bar",
      chartColor: "#ffd86a",
      values: [32, 72, 48, 36, 58],
    },
    {
      label: "新增订单数量",
      value: "300",
      compareLabel: "较上周",
      compareValue: "-30%",
      compareTone: "negative",
      chartType: "area",
      chartColor: "#ff7b75",
      values: [18, 50, 118, 86, 86, 18],
    },
    {
      label: "新增动态数量",
      value: "8890",
      compareLabel: "较昨日",
      compareValue: "+38%",
      compareTone: "positive",
      chartType: "bar",
      chartColor: "#6870f5",
      values: [18, 36, 58, 82, 108, 82],
    },
  ],
  quickEntries: [
    { title: "全部用户", icon: "users", tone: "mint", pageId: "elder/member-list" },
    { title: "报告管理", icon: "report", tone: "amber", pageId: "elder/report-management" },
    { title: "会话", icon: "message", tone: "rose", pageId: "dashboard/session" },
    { title: "全部订单", icon: "database", tone: "violet", pageId: "dashboard/order-list" },
    { title: "工单管理", icon: "file", tone: "blue", pageId: "dashboard/work-order" },
    { title: "审核管理", icon: "refresh", tone: "teal", pageId: "dashboard/review-management" },
    { title: "售后管理", icon: "star", tone: "yellow", pageId: "dashboard/after-sale" },
    { title: "动态管理", icon: "send", tone: "salmon" },
  ],
  tagDistribution: [
    { label: "高血压", value: 80, max: 140 },
    { label: "冠心病", value: 120, max: 140 },
    { label: "高血糖", value: 40, max: 140 },
    { label: "高血脂", value: 30, max: 140 },
    { label: "慢病护理", value: 110, max: 140 },
    { label: "多动症", value: 88, max: 140 },
  ],
  serviceOrderShare: [
    { label: "家政护理", value: 28, color: "#39cf9d" },
    { label: "康复理疗", value: 55, color: "#ffd557" },
    { label: "上门体检", value: 17, color: "#ff6f6a" },
  ],
  trend: {
    labels: ["03-01", "03-02", "03-03", "03-04", "03-05", "03-06", "03-07"],
    values: [3380, 2860, 3040, 1520, 3220, 2940, 3470],
    highlightIndex: 3,
    highlightValue: 1520,
    legend: "新增用户数量",
  },
  productRanking: [
    { rank: 1, title: "日常清洁 2小时1人急速清洁全程质保", orders: 1300 },
    { rank: 2, title: "日常清洁 2小时1人急速清洁全程质保", orders: 1300 },
    { rank: 3, title: "日常清洁 2小时1人急速清洁全程质保", orders: 1300 },
    { rank: 4, title: "日常清洁 2小时1人急速清洁全程质保", orders: 1300 },
    { rank: 5, title: "日常清洁 2小时1人急速清洁全程质保", orders: 1300 },
  ],
  staffRanking: [
    { rank: 1, name: "王小倩", category: "家政护工", orders: 2678 },
    { rank: 2, name: "王小倩", category: "家政护工", orders: 2678 },
    { rank: 3, name: "王小倩", category: "家政护工", orders: 2678 },
    { rank: 4, name: "王小倩", category: "家政护工", orders: 2678 },
    { rank: 5, name: "王小倩", category: "家政护工", orders: 2678 },
  ],
  productImage:
    "https://images.pexels.com/photos/9462743/pexels-photo-9462743.jpeg?auto=compress&cs=tinysrgb&w=300",
  staffAvatar:
    "https://images.pexels.com/photos/6129501/pexels-photo-6129501.jpeg?auto=compress&cs=tinysrgb&w=240",
};

export default mock;
