const avatarA =
  "https://images.pexels.com/photos/6129501/pexels-photo-6129501.jpeg?auto=compress&cs=tinysrgb&w=160";
const avatarB =
  "https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&w=160";

const mock = {
  title: "预约看板",
  defaultDate: "2026-04-29",
  staffOptions: ["全部服务人员", "李医生", "王护理", "周康复", "陈护工"],
  serviceTypeOptions: ["全部类型", "康复训练", "家政护理", "上门检测"],
  timeSlots: [9, 10, 11, 12, 13, 14, 15, 16, 17],
  bookings: [
    {
      id: "booking-1",
      date: "2026-04-29",
      title: "肌力增强训练",
      timeLabel: "9:00-10:00",
      userName: "王强",
      serviceType: "康复训练",
      staffs: ["李医生", "周康复"],
      avatars: [avatarA, avatarB],
      status: "已完成",
      tone: "amber",
      startHour: 9,
      endHour: 10,
      lane: 1,
      laneSpan: 1,
    },
    {
      id: "booking-2",
      date: "2026-04-29",
      title: "全屋清洁",
      timeLabel: "10:00-11:00",
      userName: "王强",
      serviceType: "家政护理",
      staffs: ["王护理", "陈护工"],
      avatars: [avatarA, avatarB],
      status: "服务中",
      tone: "green",
      startHour: 10,
      endHour: 11,
      lane: 1,
      laneSpan: 1,
    },
    {
      id: "booking-3",
      date: "2026-04-29",
      title: "全屋清洁",
      timeLabel: "10:00-11:00",
      userName: "王强",
      serviceType: "家政护理",
      staffs: ["王护理", "陈护工"],
      avatars: [avatarA, avatarB],
      status: "服务中",
      tone: "green",
      startHour: 10,
      endHour: 11,
      lane: 2,
      laneSpan: 1,
    },
    {
      id: "booking-4",
      date: "2026-04-29",
      title: "常规血脂检测",
      timeLabel: "12:00-13:00",
      userName: "王强",
      serviceType: "上门检测",
      staffs: ["李医生", "王护理"],
      avatars: [avatarA, avatarB],
      status: "待服务",
      tone: "red",
      startHour: 12,
      endHour: 13,
      lane: 1,
      laneSpan: 1,
    },
    {
      id: "booking-5",
      date: "2026-04-29",
      title: "凝血三项检测",
      timeLabel: "15:00-16:00",
      userName: "王强",
      serviceType: "上门检测",
      staffs: ["李医生", "王护理"],
      avatars: [avatarA, avatarB],
      status: "待服务",
      tone: "red",
      startHour: 15,
      endHour: 16,
      lane: 1,
      laneSpan: 1,
    },
  ],
} as const;

export default mock;
