import { analyticsProductImages } from "../_shared/mock-data";

const mock = {
  title: "产品分析",
  filters: [
    [
      { type: "select", label: "产品类别", placeholder: "请选择", span: 8 },
      { type: "number-range", label: "价格", startPlaceholder: "最低价格", endPlaceholder: "最高价格", span: 12 },
    ],
    [
      { type: "date-range", label: "选择日期", startPlaceholder: "请选择日期", endPlaceholder: "请选择日期", span: 10 },
      { type: "keyword", placeholder: "请输入关键字", span: 10 },
      { type: "actions", actions: ["search", "reset"], span: 4 },
    ],
  ],
  bulkActionLabel: "批量操作",
  tableMinWidth: 1520,
  columns: [
    { key: "info", label: "产品信息", width: "320px" },
    { key: "category", label: "产品\n类别", align: "center", width: "120px" },
    { key: "browse", label: "浏览\n量", align: "center", width: "108px" },
    { key: "visitors", label: "访客\n量", align: "center", width: "108px" },
    { key: "favorites", label: "收藏\n量", align: "center", width: "108px" },
    { key: "shares", label: "分享\n次数", align: "center", width: "108px" },
    { key: "payUsers", label: "支付\n人数", align: "center", width: "108px" },
    { key: "payOrders", label: "支付\n订单数", align: "center", width: "124px" },
    { key: "amount", label: "订单金额\n（元）", align: "center", width: "132px" },
    { key: "conversion", label: "访问支付\n转化率", align: "center", width: "132px" },
  ],
  rows: [
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[0],
        primary: "脑中风术后康复理疗套餐",
        secondary: "323009000",
      },
      category: "康复理疗",
      browse: 2860,
      visitors: 2408,
      favorites: 462,
      shares: 318,
      payUsers: 184,
      payOrders: 196,
      amount: "37240.00",
      conversion: "7.6%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[1],
        primary: "居家关节松动训练计划",
        secondary: "323009018",
      },
      category: "康复理疗",
      browse: 2450,
      visitors: 2102,
      favorites: 398,
      shares: 286,
      payUsers: 166,
      payOrders: 174,
      amount: "31860.00",
      conversion: "7.9%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[2],
        primary: "居家血压监测服务包",
        secondary: "323109022",
      },
      category: "健康监测",
      browse: 3210,
      visitors: 2740,
      favorites: 518,
      shares: 401,
      payUsers: 208,
      payOrders: 226,
      amount: "45120.00",
      conversion: "8.2%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[0],
        primary: "营养配餐月度方案",
        secondary: "323209036",
      },
      category: "营养膳食",
      browse: 2980,
      visitors: 2526,
      favorites: 642,
      shares: 368,
      payUsers: 198,
      payOrders: 214,
      amount: "28960.00",
      conversion: "7.8%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[1],
        primary: "长者慢病管理服务包",
        secondary: "323309045",
      },
      category: "健康管理",
      browse: 2640,
      visitors: 2284,
      favorites: 436,
      shares: 292,
      payUsers: 176,
      payOrders: 188,
      amount: "33680.00",
      conversion: "8.2%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[2],
        primary: "上门基础护理套餐",
        secondary: "323409051",
      },
      category: "生活照护",
      browse: 2360,
      visitors: 2018,
      favorites: 362,
      shares: 244,
      payUsers: 152,
      payOrders: 161,
      amount: "25760.00",
      conversion: "8.0%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[0],
        primary: "睡眠质量评估干预计划",
        secondary: "323509067",
      },
      category: "健康管理",
      browse: 2180,
      visitors: 1862,
      favorites: 308,
      shares: 225,
      payUsers: 138,
      payOrders: 145,
      amount: "24180.00",
      conversion: "7.8%",
    },
    {
      info: {
        type: "image-text",
        image: analyticsProductImages[1],
        primary: "术后营养支持组合",
        secondary: "323609073",
      },
      category: "营养膳食",
      browse: 1940,
      visitors: 1696,
      favorites: 284,
      shares: 198,
      payUsers: 126,
      payOrders: 133,
      amount: "21280.00",
      conversion: "7.4%",
    },
  ],
} as const;

export default mock;
