const mock = {
  tabs: [
    { key: 'notice', label: '通知' },
    { key: 'chat', label: '聊天' },
  ],
  notices: [
    {
      id: 1,
      title: '系统消息',
      desc: '尊敬的用户，网络波动导致财富等服务延迟，请稍后重试',
      date: '05-19',
      count: 1,
      icon: 'system',
      tone: 'purple',
    },
    {
      id: 2,
      title: '健康提醒',
      desc: '今天记得按时测量血压，并记录早晚用药情况',
      date: '05-17',
      count: 4,
      icon: 'health',
      tone: 'green',
    },
    {
      id: 3,
      title: '评论&回复',
      desc: '有人回复了你在生活圈发布的美食动态',
      date: '05-16',
      count: 3,
      icon: 'comment',
      tone: 'pink',
    },
    {
      id: 4,
      title: '关注',
      desc: '清栀、晚风记事等用户关注了你',
      date: '05-14',
      count: 7,
      icon: 'user',
      tone: 'yellow',
    },
    {
      id: 5,
      title: '赞和收藏',
      desc: '你的帖子获得了新的喜欢和收藏',
      date: '05-13',
      count: 4,
      icon: 'like',
      tone: 'violet',
    },
    {
      id: 6,
      title: '订单消息',
      desc: '订单已完成，欢迎查看服务详情并评价',
      date: '05-11',
      count: 1,
      icon: 'order',
      tone: 'mint',
    },
  ],
  chats: [
    {
      id: 4,
      title: '在线客服',
      desc: '订单进度、报告流转、到家服务都可咨询',
      date: '刚刚',
      count: 1,
      icon: 'service',
      tone: 'mint',
      pageId: 'home/customer-service-chat',
    },
    {
      id: 3,
      title: '王医生',
      desc: '可以咨询用药、康复和日常健康问题',
      date: '刚刚',
      count: 1,
      icon: 'doctor',
      tone: 'purple',
      pageId: 'home/doctor-chat',
    },
    {
      id: 1,
      title: '你的小助手',
      desc: '预约前请确认上门地址和联系电话',
      date: '05-13',
      count: 1,
      icon: 'assistant',
      tone: 'green',
      pageId: '',
    },
    {
      id: 2,
      title: '健康顾问',
      desc: '本周健康评估报告已经生成',
      date: '05-10',
      count: 2,
      icon: 'health',
      tone: 'purple',
      pageId: '',
    },
  ],
  navTabs: [
    { key: 'home', label: '首页', pageId: 'home/dashboard' },
    { key: 'circle', label: '生活圈', pageId: 'community/circle' },
    { key: 'publish', label: '', pageId: 'community/publish' },
    { key: 'message', label: '消息', pageId: 'home/message' },
    { key: 'mine', label: '我的', pageId: 'home/mine' },
  ],
}

export default mock
